batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: Models/04_sentence_recognition/202308250629
train_epochs: 1000
train_workers: 20
vocab: oFzjI-xL am1UTp"!MWtZ.E9&QuA(eli0bJ'N:6B8,D3O2Gh#RyK;rk?)sqvgPwcdnHS4C7Vf5Y
width: 1408
